### ISSUE TITLE
New ruins

### ISSUE THREAD

**Issue by Tomirad** [TheRealGangsir/Ruins#1]
Are you planned new ruins?

Or how created ruins and add to the mod?

**Comment by Sublimelime** [comment]
@Tomirad Hey there, you've stumbled upon a very outdated version of my mod. I've moved to bitbucket, the new repo is at https://bitbucket.com/Gangsir/ruins, I'm not updating this repo regularly any more.

You'll be happy to hear that several new ones have been added.
