### ISSUE TITLE
Bilka2/Ruins - LuaEntity invalid in mediumRuins

### ISSUE THREAD

**Issue by Zomis** [TheRealGangsir/Ruins#4]
As @Bilka2 /Ruins is a fork of this, I have to create this issue here.

```
Error while running the event AbandonedRuins::on_chunk_generated
LuaEntity API call when LuaEntity was invalid.
stack traceback:
mediumRuins.lua:13:in function 'm_clearArea'
mediumRuins.lua:46:in function 'spawnMediumRuins'
control.lua:38 in function control.lua:13
```

The fix is very easy, instead of:

`if entity.type ~= "resource" and entity.valid then`

do:

`if entity.valid and entity.type ~= "resource" then`

**Comment by Zomis** [comment]
The problem was (in a way, in another way just not fixed correctly) here: https://github.com/Bilka2/Ruins/commit/d4eaaff59ae4b30ad7138a2bb153ac188408d972

And also affects smallRuins and largeRuins as well.

**Comment by Zomis** [comment]
PR: https://github.com/Bilka2/Ruins/pull/2

**Comment by Bilka2** [comment]
Oops, thanks for that. I'll update my version.
